FROM python:3.11-slim

# directory of the container
WORKDIR /app

# copy everything from that root to the workdirectory
COPY src/api/ .

# install the modules
RUN pip install -r requirements.txt

# copy all the files that end in pkl into the location
RUN mkdir -p models/trained/
COPY models/trained/*.pkl models/trained/

# export the port
EXPOSE 8000

# run the command for make work Fast api
CMD ["uvicorn",  "main:app",  "--host",  "0.0.0.0",  "--port",  "8000"]
