name: Streamlit CI

# when we execute the pipeline
on:
  push:
    # we execute this pipeline when this folder change
    paths:
      - 'streamlit_app/**'
  workflow_dispatch:

# jobs or steps that we need to finish this job
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    # steps of the job
    steps:
      # Downloads the repository code onto the runner, making files accessible.
      - name: Checkout code
        uses: actions/checkout@v4

      # Sets up Docker Buildx, enabling advanced Docker features like enhanced caching and multi-platform builds.  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      # Authenticates with Docker Hub to allow pushing the final image.
      - name: Log in to DockerHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      #  build the image the streamlit app and put it in the dockerhub
      - name: Build and push Streamlit Docker image
        uses: docker/build-push-action@v5
        with:
          context: . 
          file: Dockerfile.streamlit 
          # Instructs the action to push the built image to Docker Hub.
          push: true
          tags: docker.io/${{ vars.DOCKERHUB_USERNAME }}/streamlit:latest